print(f"We are good friends")
print("MAJOR PROJECT")
print("we are doing the major project in group of 4")
print("Placify - platform")
print("Bhoomika C")
print("We work together")
print("Placify - platform")
